name: adult-spine-models
channels:
  - defaults
dependencies:
  - python=3.7
  - jupyterlab
  - numpy
  - scipy
  - h5py
  - matplotlib
  - seaborn
  - xarray
  - statsmodels
  - ipdb
  - statannotations
prefix: C:\Users\Gregg\anaconda3\envs\adult-spine-models
